# Generated by Django 5.2.1 on 2025-05-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='mobile_no',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
